/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a6c8ff",
        "surface": "#f7f9fb",
        "surface-variant": "#e1e2e8",
        "tertiary-container": "#ffdbcb",
        "on-secondary-container": "#131c2b",
        "on-surface": "#1a1b20",
        "on-tertiary-fixed-variant": "#5e2900",
        "surface-container-highest": "#e3e2e6",
        "inverse-on-surface": "#f1f0f4",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#a6c8ff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d3e3ff",
        "primary-container": "#d3e3ff",
        "background": "#f7f9fb",
        "outline-variant": "#c4c6d0",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2f3036",
        "on-primary-container": "#001b3f",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed-variant": "#00458e",
        "outline": "#74777f",
        "secondary-fixed": "#dae2f9",
        "on-primary": "#ffffff",
        "on-background": "#1a1b20",
        "tertiary-fixed-dim": "#ffb690",
        "secondary-container": "#dae2f9",
        "tertiary-fixed": "#ffdbcb",
        "on-tertiary-container": "#2c1000",
        "primary": "#2563eb",
        "secondary": "#565e71",
        "surface-bright": "#f7f9fb",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-tint": "#2563eb",
        "on-tertiary-fixed": "#2c1000",
        "secondary-fixed-dim": "#bec6dc",
        "on-secondary-fixed-variant": "#3e4759",
        "on-secondary-fixed": "#131c2b",
        "on-surface-variant": "#44474e",
        "surface-container": "#ecedf1",
        "on-primary-fixed": "#001b3f",
        "surface-container-high": "#e7e8ec",
        "on-error-container": "#410002",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#7d5700",
        "on-error": "#ffffff",
        "severity-critical": "#dc2626",
        "severity-warning": "#d97706",
        "severity-safe": "#059669",
        "severity-info": "#2563eb",

        // Dark Command Center Theme tokens
        "dark-surface": "#0f131c",
        "dark-surface-container": "#1c2029",
        "dark-surface-container-high": "#262a34",
        "dark-surface-container-low": "#181b25",
        "dark-surface-container-lowest": "#0a0e17",
        "dark-on-surface": "#dfe2ef",
        "dark-on-surface-variant": "#c2c6d6",
        "dark-outline-variant": "#424754",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-page": "24px",
        "gutter": "16px",
        "panel-padding": "12px",
        "unit": "4px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "label-mono-bold": ["Geist Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-mono": ["Geist Mono", "monospace"],
        "data-metric": ["Geist Mono", "monospace"],
        "mono": ["Geist Mono", "monospace"],
        "sans": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
};
